apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: auto-instrumentation
  namespace: observability
spec:
  # CRITICAL: Point to OTel Collector, not directly to backends
  exporter:
    endpoint: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318

  # Propagation headers for distributed tracing
  propagators:
    - tracecontext # W3C standard
    - baggage # Carry metadata across services
    - b3 # Zipkin-style (for legacy compatibility)

  # Sampling strategy (adjust based on traffic volume)
  sampler:
    type: parentbased_traceidratio # Respects parent decision, then samples by ratio
    argument: "1.0" # 1.0 = 100% (reduce to 0.1 for 10% in production)

  # Resource attributes (identify your service across all telemetry)
  resource:
    addK8sUIDAttributes: true # Add Kubernetes metadata automatically

  # Java instrumentation (Spring Boot, Micronaut, etc.)
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      # Force HTTP/protobuf (more reliable than gRPC in K8s)
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      # Enable all signal types
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      # Capture SQL queries (sanitized)
      - name: OTEL_INSTRUMENTATION_JDBC_STATEMENT_SANITIZER_ENABLED
        value: "true"
      # Capture HTTP headers (exclude sensitive ones)
      - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST
        value: "content-type,user-agent"

  # Node.js instrumentation (Express, Fastify, etc.)
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      # Capture detailed HTTP info
      - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST
        value: "content-type,authorization"
